server:
  port: 10013
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_mybatis?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mapper:
  mappers: com.lxx.auto.base.BaseMapper
  not-empty: false
  identity: MYSQL
# mybatis相关路径配置
mybatis:
  type-aliases-package: com.lxx.auto.entity
  mapper-locations: classpath*:mapping/*.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
# 自动建表
actable.table.auto: update
actable.model.pack: com.lxx.auto.entity
actable.database.type: mysql


